Import Library

In [1]:
import pandas as pd
import numpy as np 

In [2]:
df=pd.read_csv(r'https://raw.githubusercontent.com/YBI-Foundation/Dataset/main/Diabetes.csv')

In [3]:
df.head()

pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age  \
0            6      148         72       35        0  33.6  0.627   50   
1            1       85         66       29        0  26.6  0.351   31   
2            8      183         64        0        0  23.3  0.672   32   
3            1       89         66       23       94  28.1  0.167   21   
4            0      137         40       35      168  43.1  2.288   33   

   diabetes  
0         1  
1         0  
2         1  
3         0  
4         1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   pregnancies  768 non-null    int64  
 1   glucose      768 non-null    int64  
 2   diastolic    768 non-null    int64  
 3   triceps      768 non-null    int64  
 4   insulin      768 non-null    int64  
 5   bmi          768 non-null    float64
 6   dpf          768 non-null    float64
 7   age          768 non-null    int64  
 8   diabetes     768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [5]:
df.describe()

pregnancies     glucose   diastolic     triceps     insulin  \
count   768.000000  768.000000  768.000000  768.000000  768.000000   
mean      3.845052  120.894531   69.105469   20.536458   79.799479   
std       3.369578   31.972618   19.355807   15.952218  115.244002   
min       0.000000    0.000000    0.000000    0.000000    0.000000   
25%       1.000000   99.000000   62.000000    0.000000    0.000000   
50%       3.000000  117.000000   72.000000   23.000000   30.500000   
75%       6.000000  140.250000   80.000000   32.000000  127.250000   
max      17.000000  199.000000  122.000000   99.000000  846.000000   

              bmi         dpf         age    diabetes  
count  768.000000  768.000000  768.000000  768.000000  
mean    31.992578    0.471876   33.240885    0.348958  
std      7.884160    0.331329   11.760232    0.476951  
min      0.000000    0.078000   21.000000    0.000000  
25%     27.300000    0.243750   24.000000    0.000000  
50%     32.000000    0.372500   29.000000    0.000000  
75%     36.600000    0.626250   41.000000    1.000000  
max     67.100000    2.420000   81.000000    1.000000

In [6]:
df.columns

Index(['pregnancies', 'glucose', 'diastolic', 'triceps', 'insulin', 'bmi',
       'dpf', 'age', 'diabetes'],
      dtype='object')

In [8]:
df.shape

(768, 9)

In [9]:
df['diabetes'].value_counts()

0    500
1    268
Name: diabetes, dtype: int64

In [10]:
df.groupby('diabetes').mean()

pregnancies     glucose  diastolic    triceps     insulin  \
diabetes                                                              
0            3.298000  109.980000  68.184000  19.664000   68.792000   
1            4.865672  141.257463  70.824627  22.164179  100.335821   

                bmi       dpf        age  
diabetes                                  
0         30.304200  0.429734  31.190000  
1         35.142537  0.550500  37.067164

Define X and Y

In [12]:
y=df['diabetes']

In [13]:
y.shape

(768,)

In [14]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: diabetes, Length: 768, dtype: int64

In [22]:
x=df.drop('diabetes',axis=1)

In [23]:
x.shape

(768, 8)

# Scaling

In [27]:
from sklearn.preprocessing import MinMaxScaler

In [28]:
mm=MinMaxScaler()

In [29]:
x=mm.fit_transform(x)

In [30]:
x

array([[0.35294118, 0.74371859, 0.59016393, ..., 0.50074516, 0.23441503,
        0.48333333],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.39642325, 0.11656704,
        0.16666667],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.34724292, 0.25362938,
        0.18333333],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.390462  , 0.07130658,
        0.15      ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.4485842 , 0.11571307,
        0.43333333],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.45305514, 0.10119556,
        0.03333333]])

# Train Test Split

In [31]:
from sklearn.model_selection import train_test_split

In [34]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,random_state=2429)

In [35]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((537, 8), (231, 8), (537,), (231,))

# Logistic Regression

In [36]:
from sklearn.linear_model import LogisticRegression

In [38]:
lr=LogisticRegression()

In [39]:
lr.fit(x_train,y_train)

LogisticRegression()

# Prediction

In [40]:
y_pred=lr.predict(x_test)

In [41]:
y_pred.shape

(231,)

# Probability of each predicted class

In [42]:
lr.predict_proba(x_test)

array([[0.57611081, 0.42388919],
       [0.90906577, 0.09093423],
       [0.67315282, 0.32684718],
       [0.3981702 , 0.6018298 ],
       [0.83353778, 0.16646222],
       [0.8225342 , 0.1774658 ],
       [0.67343296, 0.32656704],
       [0.34050344, 0.65949656],
       [0.3843026 , 0.6156974 ],
       [0.68867017, 0.31132983],
       [0.82303951, 0.17696049],
       [0.8701324 , 0.1298676 ],
       [0.42972565, 0.57027435],
       [0.73042875, 0.26957125],
       [0.73321682, 0.26678318],
       [0.80751951, 0.19248049],
       [0.44379129, 0.55620871],
       [0.17096691, 0.82903309],
       [0.31705838, 0.68294162],
       [0.51172086, 0.48827914],
       [0.84332429, 0.15667571],
       [0.45307062, 0.54692938],
       [0.20223418, 0.79776582],
       [0.67194616, 0.32805384],
       [0.95033548, 0.04966452],
       [0.76492979, 0.23507021],
       [0.85959686, 0.14040314],
       [0.73672391, 0.26327609],
       [0.25090418, 0.74909582],
       [0.88236089, 0.11763911],
       [0.

# Model Evaluation

In [43]:
from sklearn.metrics import confusion_matrix,classification_report

In [44]:
print(confusion_matrix(y_test,y_pred))

[[132  15]
 [ 38  46]]


In [45]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.78      0.90      0.83       147
           1       0.75      0.55      0.63        84

    accuracy                           0.77       231
   macro avg       0.77      0.72      0.73       231
weighted avg       0.77      0.77      0.76       231



# Get Future Predictions

In [48]:
x_new=df.sample(1)

In [50]:
x_new

pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age  \
667           10      111         70       27        0  27.5  0.141   40   

     diabetes  
667         1

In [51]:
x_new.shape

(1, 9)

In [52]:
x_new=x_new.drop('diabetes',axis=1)

In [53]:
x_new=mm.fit_transform(x_new)

In [54]:
y_pred_new=lr.predict(x_new)

In [55]:
y_pred_new

array([0], dtype=int64)

In [56]:
lr.predict_proba(x_new)

array([[0.99486094, 0.00513906]])