In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df=pd.read_csv(r'https://raw.githubusercontent.com/YBI-Foundation/Dataset/main/Spam%20Email.csv')

In [4]:
df.head()

ID Mail                                               Text  Label
0   1  ham          Subject: christmas tree farm pictures\r\n      0
1   2  ham  Subject: vastar resources , inc .\r\ngary , pr...      0
2   3  ham  Subject: calpine daily gas nomination\r\n- cal...      0
3   4  ham  Subject: re : issue\r\nfyi - see note below - ...      0
4   5  ham  Subject: meter 7268 nov allocation\r\nfyi .\r\...      0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5171 entries, 0 to 5170
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   ID      5171 non-null   int64 
 1   Mail    5171 non-null   object
 2   Text    5171 non-null   object
 3   Label   5171 non-null   int64 
dtypes: int64(2), object(2)
memory usage: 161.7+ KB


In [8]:
df.columns

Index(['ID', 'Mail', 'Text', 'Label'], dtype='object')

In [9]:
df.shape

(5171, 4)

# Define X and Y


In [10]:
y=df['Label']

In [11]:
y.shape

(5171,)

In [12]:
y

0       0
1       0
2       0
3       0
4       0
       ..
5166    1
5167    1
5168    1
5169    1
5170    1
Name: Label, Length: 5171, dtype: int64

In [13]:
x=df['Text']

In [14]:
x.shape

(5171,)

In [16]:
x

0               Subject: christmas tree farm pictures\r\n
1       Subject: vastar resources , inc .\r\ngary , pr...
2       Subject: calpine daily gas nomination\r\n- cal...
3       Subject: re : issue\r\nfyi - see note below - ...
4       Subject: meter 7268 nov allocation\r\nfyi .\r\...
                              ...                        
5166    Subject: our pro - forma invoice attached\r\nd...
5167    Subject: str _ rndlen ( 2 - 4 ) } { extra _ ti...
5168    Subject: check me out !\r\n61 bb\r\nhey derm\r...
5169    Subject: hot jobs\r\nglobal marketing specialt...
5170    Subject: save up to 89 % on ink + no shipping ...
Name: Text, Length: 5171, dtype: object

# Train Test Split

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,stratify=y,random_state=2529)

In [19]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((3619,), (1552,), (3619,), (1552,))

# X variable features extraction

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [29]:
tfidf= TfidfVectorizer (min_df=1,stop_words='english',lowercase='True')

In [30]:
x_train_features=tfidf.fit_transform(x_train)

In [31]:
x_test_features=tfidf.transform(x_test)

In [32]:
x_train

4367    Subject: time sensitive . . . refer to # f 781...
3849    Subject: homeowners - get more money in your p...
2199    Subject: calpine daily gas nomination\r\n>\r\n...
2057    Subject: holiday invitation\r\nplease click on...
3019    Subject: first deliveries - comstock oil & gas...
                              ...                        
579     Subject: new update for buybacks\r\nthere are ...
4280    Subject: get it free - ibm thinkpad computer !...
3909    Subject: buckhorn doberman\r\nhello . i did no...
2133    Subject: galleryfurniture . com bowl\r\nenron ...
4508              Subject: want a new playstation 2 ?\r\n
Name: Text, Length: 3619, dtype: object

In [33]:
x_train_features

<3619x40400 sparse matrix of type '<class 'numpy.float64'>'
	with 237060 stored elements in Compressed Sparse Row format>

# Train Model

In [34]:
from sklearn.ensemble import RandomForestClassifier

In [35]:
rf=RandomForestClassifier(random_state=2529)

In [36]:
rf.fit(x_train_features,y_train)

RandomForestClassifier(random_state=2529)

# Model Prediction

In [37]:
y_pred=rf.predict(x_test_features)

In [38]:
y_pred.shape

(1552,)

In [39]:
y_pred

array([0, 1, 0, ..., 1, 0, 0], dtype=int64)

# Probabilty of each predicted class

In [40]:
rf.predict_proba(x_test_features)

array([[0.99, 0.01],
       [0.1 , 0.9 ],
       [0.72, 0.28],
       ...,
       [0.3 , 0.7 ],
       [0.89, 0.11],
       [0.68, 0.32]])

# Model Evaluation

In [41]:
from sklearn.metrics import confusion_matrix,classification_report

In [42]:
print(confusion_matrix(y_test,y_pred))

[[1081   21]
 [  15  435]]


In [43]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      0.98      0.98      1102
           1       0.95      0.97      0.96       450

    accuracy                           0.98      1552
   macro avg       0.97      0.97      0.97      1552
weighted avg       0.98      0.98      0.98      1552

